# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "352e3b904aaefa00ca6e2c3b836880ba"
name = "Mcobeauty Us"
application_url = "https://implementation-cgi-consultancy-really.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ] 
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_orders,write_orders,read_cart_transforms,write_cart_transforms,write_discounts,read_discounts"

[auth]
redirect_urls = [ "https://implementation-cgi-consultancy-really.trycloudflare.com/api/auth" ]
